language: java
jdk: oraclejdk8

env:
  global:
    - ANDROID_API=28
    - ANDROID_BUILD_TOOLS=28.0.3
    - EMULATOR_ARCH=armeabi-v7a
    - ANDROID_SDK_ROOT=$HOME/android-sdk

    # Pointless in CI.
    - QEMU_AUDIO_DRV=none

    # Disable the daemon -- we only run Gradle once. This ensures that all of its files are
    # properly unlocked for caching.
    - GRADLE_OPTS=-Dorg.gradle.daemon=false

jobs:
  include:
    # This only runs "assemble", which compiles the code. This is normally fast -- and allows
    # quick feedback in case of compiler errors (before running the more expensive test cases).
    #
    # This is run in parallel (debug + dev + release)
    - stage: assemble
      install: ./.travis/install_android_sdk.sh
      script: ./gradlew assembleDebug
    - install: ./.travis/install_android_sdk.sh
      script: ./gradlew assembleDev
    - install: ./.travis/install_android_sdk.sh
      script: ./gradlew assembleRelease

    # This runs the full test suite, including using the Android emulator.
    - stage: test
      env: EMULATOR_API=16
    - env: EMULATOR_API=18
    # Disabled due to https://issuetracker.google.com/issues/134845202
    # - env: EMULATOR_API=21
    - env: EMULATOR_API=23
    - env: EMULATOR_API=24
    - env: EMULATOR_API=24 EMULATOR_ARCH=arm-v8a
    # Not available in vanilla flavour
    # - env: EMULATOR_API=27

# Android caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

    # Selectively cache the installed Android SDK.
    # Contrary to Travis CI's docs, the slow part is "installing" (particularly scanning remote
    # repositories). This turns "installing the SDK" into a very simple download and extract
    # operation (much simpler than what sdkmanager does).
    - $HOME/android-sdk/build-tools/$ANDROID_BUILD_TOOLS
    - $HOME/android-sdk/extras
    - $HOME/android-sdk/fonts
    - $HOME/android-sdk/licenses
    - $HOME/android-sdk/patcher
    - $HOME/android-sdk/platforms/android-$ANDROID_API
    - $HOME/android-sdk/tools

    # Android test environment.
    # Travis keeps a cache per environment, so lets cache emulators!
    - $HOME/android-sdk/emulator
    - $HOME/android-sdk/platform-tools
    - $HOME/android-sdk/system-images/android-$EMULATOR_API/default/$EMULATOR_ARCH

install:
  - ./.travis/install_android_sdk.sh
  - ./.travis/install_android_emulator.sh
